### PR TITLE
Update readme.md - dinner

### PR DESCRIPTION
**Pull request by amypaddle1**
## 🎯 Objective

Formatting and image

## 🛠️ Changes made

- Formatted the ingredients into a bullet list
- Added an image bc why not 👀 😆 

## 👥 Who needs to review this Pull Request? 

@gurbuxlohana
@rnagpal991
@carolinadarraidou 
@p-mullangi

### CODE REVIEW

**Review by p-mullangi — APPROVED** [review]
Thanks for adding formatting! Looks great.

**Review by gurbuxlohana — APPROVED** [review]
Looks good

**Review by rnagpal991 — APPROVED** [review]

**Comment by rnagpal991** [comment]
Looks good!

**Review by gurbuxlohana — APPROVED** [review]

**Review by gurbuxlohana — COMMENTED** [review]
commit

**Pull request merged**
